// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDppNNChINM43TuwHXM4Ca2QLb21mtoisE',
    appId: '1:279502067148:web:cc7cdcd83525dc4172b969',
    messagingSenderId: '279502067148',
    projectId: 'tugasmcc-5aa23',
    authDomain: 'tugasmcc-5aa23.firebaseapp.com',
    storageBucket: 'tugasmcc-5aa23.firebasestorage.app',
    measurementId: 'G-6E6Z8V9LWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKOs55phTEB4cDnIn_HpZeQ6AUqSw09E',
    appId: '1:279502067148:android:7b0c73b732b853e572b969',
    messagingSenderId: '279502067148',
    projectId: 'tugasmcc-5aa23',
    storageBucket: 'tugasmcc-5aa23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmiDuloWtZwEI0BzZOv6iAsOkktP04S1o',
    appId: '1:279502067148:ios:104838576b7b6f8672b969',
    messagingSenderId: '279502067148',
    projectId: 'tugasmcc-5aa23',
    storageBucket: 'tugasmcc-5aa23.firebasestorage.app',
    iosBundleId: 'com.toyshop.toyshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmiDuloWtZwEI0BzZOv6iAsOkktP04S1o',
    appId: '1:279502067148:ios:104838576b7b6f8672b969',
    messagingSenderId: '279502067148',
    projectId: 'tugasmcc-5aa23',
    storageBucket: 'tugasmcc-5aa23.firebasestorage.app',
    iosBundleId: 'com.toyshop.toyshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDppNNChINM43TuwHXM4Ca2QLb21mtoisE',
    appId: '1:279502067148:web:89be150d203598df72b969',
    messagingSenderId: '279502067148',
    projectId: 'tugasmcc-5aa23',
    authDomain: 'tugasmcc-5aa23.firebaseapp.com',
    storageBucket: 'tugasmcc-5aa23.firebasestorage.app',
    measurementId: 'G-FWWQ1X435F',
  );
}
